[project]
name = "finer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "accelerate>=1.10.1",
    "dotenv>=0.9.9",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "torch>=2.8.0",
    "transformers>=4.57.3",
]
[tool.pyright]
venvPath = '.'
venv = '.venv'
